### ISSUE TITLE
Request: Make options for the plugin

### ISSUE THREAD

**Issue by DanGM96** [kantord/eslint-plugin-write-good-comments#3]
Hello!

This plugin would benefit for being more configurable by the examples given here: https://github.com/btford/write-good#api

For my case, I'd like to be able to turn off "passive" warnings, but keep the rest. But being able to configure the other stuff would be very nice, such as "checks".

**Comment by kantord** [comment]
> Hello!
> 
> This plugin would benefit for being more configurable by the examples given here: https://github.com/btford/write-good#api
> 
> For my case, I'd like to be able to turn off "passive" warnings, but keep the rest. But being able to configure the other stuff would be very nice, such as "checks".

PR is welcome for this.

Should be fairly easy too btw, after all all that should be needed is to expose this option through the eslint config and pass it along to writegood, probably like 2 lines need to be changed.

Here's how to add an option in eslint: https://eslint.org/docs/latest/extend/custom-rules#options-schemas

Here's the line where the options have to be passed to `writegood`: https://github.com/kantord/eslint-plugin-write-good-comments/blob/main/lib/rules/write-good-comments.js#L5

**Comment by kantord** [comment]
so this is now fixed, @DanGM96 ?

**Comment by DanGM96** [comment]
Yes, now we can configure the plugin as we see fit 🙂
We can close this issue now.
